name: Weekly Issue Creator

on:
  schedule:
    # Chạy vào mỗi thứ Hai lúc 9:00 UTC
    - cron: '0 9 * * 1'

permissions:
  contents: read
  issues: write

jobs:
  create_weekly_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Weekly Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_REMINDER.md
